name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: architectural_design_specification.tex
          args: 
                -pdf -file-line-error -halt-on-error -interaction=nonstopmode 
       - name: Archive Logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: logs
          path: main.log
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: architectural_design_specification.pdf

